version: "3.9"
services:
  flask_app:
    command: bash -c " 
        python init_db.py 
        && flask run
      "
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/flask_app
    ports:
      - "5000:5000"